### ISSUE TITLE
Update for beats v6 compatibility

### ISSUE THREAD

**Issue by geekpete** [dadoonet/soundbeat#3]
Beats has changed a bit since the original implementation, would be great to see the blog post updated to be relevant to beats v6 and corresponding code updated for compatibility with the latest release.

Also since this https://github.com/elastic/kibana/pull/6796 now allows sub-second aggs, perhaps remove the workaround from the original beat implementation (zoom field).

**Comment by dadoonet** [comment]
I did a PR in #5.
Note that the code already removed the `zoom` factor while back with https://github.com/dadoonet/soundbeat/commit/e5e9a92c77798796be96bffee78924abee0512ee when I updated to 5.0.

I just never updated my blog post. :)
